services:
    postgres:
        image: postgres:17
        ports:
            - '5432:5432'
        environment:
            PGPASSWORD: admin
            POSTGRES_DB: rhpharma
            POSTGRES_USER: rhpharma
            POSTGRES_PASSWORD: admin
        volumes:
            - pgdata:/var/lib/postgresql/data
volumes:
    pgdata:

