services:
    postgres:
        image: 'postgres:12'
        ports:
            - '5432:5432'
        environment:
            PGPASSWORD: admin
            POSTGRES_DB: rhpharma
            POSTGRES_USER: rhpharma
            POSTGRES_PASSWORD: admin
        volumes:
            - sail-pgsql:/var/lib/postgresql/data
volumes:
    sail-pgsql:

